#!/bin/bash

duration=1
x=0
while :
do
    temp=$(cat /sys/devices/virtual/thermal/thermal_zone0/temp)
    offduty=$(cat /sys/class/pwm/pwmchip2/pwm0/duty_cycle)
    if [[ $offduty -ge 30000 ]]
        then
            echo $(date +"%T") "Temp:"$temp "Fan speed:"0%
        else
            #echo "Offduty:"$offduty
            fanspeed=$(((40000 - $offduty) * 100 / 40000))
            echo $(date +"%T") "Temp:"$temp "Fan speed:"$fanspeed"%"
    fi
    if [[ $x -ge 3 ]]
        then
            duration=$(($duration*2))
            x=0
    fi
    if [[ $duration -ge 240 ]]
        then
            duration=240
    fi
    #echo "Duration:"$duration "x:"$x
    sleep $duration
    x=$(($x+1))
done
